Buttons/icon_button_rounded.html
Round button with the icon for issue #11
=> Create a Icon Button Rounded

Buttons/button_with_icon_secondary.html
This is my fix :)
Button added!
=> Button with icon secondary added

Buttons/button_with_icon_end.html
Here is the component I have built for issue #9 . 
=> Added the button with icon component

Buttons/button_secondary.html
Done Issue No #13 
Screen Sort:
=> Created a Secondary Button

Buttons/button_secondary_with_icon.html
=> Added secondary button with icon

Store Buttons/google_play_store_button.html
=> Create store button for google play

Buttons/icon_button_secondary.html
Description:
Added new icon_button_secondary html file with tailwindcss
Issue: #21 
Screenshot:
=> icon button secondary added

Pagination/index.html
Done Issue No #31 
screenshot:
=> Pagination Added

Tutorial.md
Hopefully this does a good enough job with the points you mentioned in issue 6.
this commit fixes #6
=> Issue#6 First draft of tutorial page

Tables/table_primary.html
=> Add primary table

Feedback Form/index.html
=> Added Feedback form

Buttons/ic0n_button_rounded.html
=> Added Icon

Book appointment component/index.html
=> Added Book Appointment component

Footer/index.html
=> Added Footer with social links

Testimonials/index.html
Issue #71 
Created the testimonials component.
Used tailwindcss.
=> created the testimonials component

Content Cards/index.html
=> Content Card Created

Alerts/bell-notification.html
=> Add bell-notification component

Buttons/button_primary_rounded.html
Adds a rounded primary button component.
Signed-off-by: Aabhas Sao <aabhassao0@gmail.com>
=> feat: add primary button rounded

Dropdown/index.html
I added the dropdown button 
Closes #95
=> dropdown button added

Pricing Components/index.html
=> Added Pricing component

Filters/mobile/marketplace-1.html
=> mobile filter marketplace added

README.md
=> Added contributors section #7

Feature Cards/features-card-small-v2.html
Issue #120 
I have created the Simple_Features_Card v2.
Snapshot
=> Simple-Features-Card v2

Feature Cards/feature-cards-job-security2.html
=> Created job security card-2 #121

Contact/Form-card-4/index.html
=> added form-card-4 (subscribe newsletter)

Feature Cards/feature-card-big-outlined.html
Added new HTML & TailwindCSS component mentioned in  #116 
Preview:
=> Created a feature card (big outlined) component

Contact/contact2.html
=> Added contact2.html

Feature Cards/simple-features-card-small.html
Here is the component I have built.
=> Created simple-features-card-small Issue #110

Feature Cards/feature-card-image.html
assigned issue#112
screenshot:
=> feature-card-image.html

Navbar/nav1.html
=> Added a Navigation Bar

Feature Cards/feature-card-job -security-filled.html
Created Job Security Card component using HTML and Tailwind CSS
=> Created Job Security Card

Navbar/nav2.html
=> Added a second Navigation Bar

Feature Cards/feature-card-large-outlined-button.html
=> feature-card-large-outlined-button.html

Testimonials/testimonial-v5.html
issue #161 testimonial-v5.html
screenshot:
screenshot contains border around the card for proper visibility of the card ,but  testimonial-v5.html file does not contain borders.
=> testimonial-v5.html

Contact/contact-book-appointment.html, Inputs/textarea.html, Testimonials/testimonial-v1.html
=> Added contact component

Inputs/textarea.html, Testimonials/testimonial-v1.html
=> Web UI Testimonial V1

Navbar/Navbar-Mobile/navbar-style-1-navbar-light/index.html
Here is the component I have built.  #177 
mobile-navbar
=> Added mobile navbar

Testimonials/testimonial-v6.html
Description:
Testimonial v6 added
Issue: #162 
Screenshot:
=> Testimonial v6 added

Pricing Components/Pricing-Component-5.html
=> Pricing Component 5 added

Pricing Components/pricingstyle-3.html
Hi, I have completed working on issue #150  assigned to me.
Here is the component I have built.
This is the component from the Figma file.
Here is a screenshot of the coded version built on Tailwind Play
I have used Hero Icons as instructed for the 'check' icons.
Here is a screenshot of the code.
I have tried to replicate the Figma design as much as possible. I have added a file in the 'Pricing Components' directory named 'pricing-style-3'.
Kindly review this PR and let me know if approved or if any changes are required.
Thank you,
Abir
=> Added Component pricing-style-3

Pricing Cards/pricing_card1.html
Regarding #81 
Hey, I created a pricing card using HTML including tailwind CSS 
Images 
kindly review this PR
=> Pricing_Card1.html added in Pricing Cards folder

Testimonials/testimonial-v4.html
Resolve #167 
Here is the testimonial v4 I have built. 
Here is a reference to the component.
=> Create a testimonial v4

Content Cards/content-card-item-5.html
Created Content Card-5 using HTML and Tailwind CSS.
Below is the Screenshot for the component
=> Content card

Alerts/check_alert.html
Check alert created and pushed in the Alerts folder
file name - check_alert.html
Thanks 😄
=> Check Alert added 

Feature Cards/Feature_card_BrandName.html
Status - BrandName Feature Card Created and added to Feature Cards Folder 
Kindly review it
Thanks ♥
=> BrandName Feature card Added

.github/ISSUE_TEMPLATE/Feature_Request.md
=> Added Feature Request Template under Issue Templates

Inputs/textarea-v2.html
=> Added textarea-v2.html

Alerts/alert_info_notification.html, Alerts/alert_notification_danger.html
Added new UI kit for alert notification (danger / error one)
=> new alert notification danger ui added

Form groups/form-group-category-form-group.html
=> Added Code for Category form group

Alerts/alert_warning_notification.html
Alert Notification for Warning
=> Warning Alert notification created

Form groups/form-group-category-form-group.html, Form groups/form-groups-search-form-group1.html
=> Search Form UI Added

Feature Cards/feature-card-item-17.html
Created feature card item-17 component using HTML and Tailwind CSS
Here is the screenshot of the created component
=> Created Feature card 17

Content Cards/content-card-9.html
Created content-card-item-9 using HTML and Tailwind CSS
Below is the screenshot of the created component
=> Created content card item 9

Feature Cards/feature-card-item-18.html
Created feature-card-item-18 using HTML and Tailwind CSS
Below is the screenshot for the component created
=> Created Feature card-18

Feature Cards/feature-card-item-22.html, Form groups/search-filter-category.html
=> Form groups/search-filter-category added

Filters/mobile/marketplace-3.html
Here is the component I have created-
=> Create marketplace-3.html (mobile filter)

Feature Cards/feature-cards-job-security1.html
=> Added feature card job security 1

Content Cards/content_card_item_3.html
Hey, I have worked on the component specified in the ISSUE #264 
Here is the screenshot of the same
Link of the image used : https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80
Things from my side : 
1. I have used a slightly darker overlay(gradient) for the Image as it had a nice look agains text with white font.
=> Added Content Card 3

Contact/contact3.html
Created this contact for appointment component using HTML5 & TAILWIND CSS...
here how's the component look
=> Created contact3.html file

Navbar/nav3.html
Here is the navbar-3 I have built. 
=> Add navbar-3

Form groups/choose-file.html
Here is the component I have built.
=> Create a Feature Card - Choose File #224

Widgets/List-item-2/index.html
=> added list item 2

Product Cards/product-card-item-4.html
Created product card 4 using HTML and Tailwind CSS.
Below is the Screenshot of the component created
=> Created product card 4

Navbar/Nav-mobile/nav-7.html
#285 
@Rajdip019  Please review this
=> Added Mobile Nav 7

Navbar/nav-mobile/nav-6.html
Added new HTML & TailwindCSS component mentioned in #283 
Preview:
=> Created Mobile Nav 6 Component

Testimonials/testimonial-v7.html
Added new HTML & TailwindCSS component mentioned in #163 
Preview:
=> Created Testimonial V7 Component

Navbar/Nav-mobile/nav-4.html
=> nav-4.html

Navbar/nav-mobile/nav-2.html
=> Created mobile navbar

Product Cards/product-item-5.html
Created product-item-5 using HTML and Tailwind CSS
Below is the screenshot of the component created.
=> Created product-item-5

Product Cards/product_card_1.html
Hey, I have worked on the component specified in the ISSUE #294 
Here is the screenshot of the same
Image used in the component : https://images.unsplash.com/photo-1647880087459-30f07c4faba5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2232&q=80
=> Created Product Card-1

Navbar/navbar-nav5.html
Closes #284 
The screenshot can be viewed here!
https://user-images.githubusercontent.com/92046906/196524489-ef51e603-7cfd-4228-83c3-8ae63525c457.jpeg
@Rajdip019 Please review!
=> Added Navbar-nav5.html

Form/form-notearea2-form.html
Added new HTML & TailwindCSS component mentioned in #320 
Preview:
=> Created notearea2 form component

Form/form-select-option-form.html
Created a Form Select Component using html & tailwindcss as mentioned in #316
=> Created a Form Select Component

Filters/desktop/marketplace-3.html
I have created marketplace-3 under the section desktop filter , which no one has completed till now.
screenshot:
=> marketplace-3.html

Form/form-notearea-1-form.html, Form/form-search-form.html
=> Search ui Added

Widgets/List-item-2/widget-2.html, Widgets/List-item-2/widget.html
Here is the component I have created -->
=> Create a Widget Item with icons

Form/form-messagearea-form.html
Issue #321
Message Area Form Component
=> Create Message Area Form

Filters/mobile/marketplace_filter_3_1.html
=> marketplace_filter_3_1.html

Filters/mobile/marketplace_product_1.html
=> marketplace_product_1.html

Filters/mobile/marketplace_product_2.html
=> marketplace_product_2.html

Filters/mobile/marketplace_filter_3_2.html
=> marketplace_filter_3_2.html

Form/form-email-form.html
Created email form component using HTML5 & Tailwind CSS
here's the screenshot of the component
=> Created form-email-form.html

Form/form-search-large-form1.html
=> form-search-large-form1.html

Filters/mobile/marketplace_filter_3_3.html
=> marketplace_filter_3_3.html

Content Cards/Content-card-7.html
=> Content-card-7.html

Content Cards/content-card-2.html
Created Content-card-2
Below is the screenshot of the component
=> Created content-card-2

Filters/mobile/marketplace_product_3.html
=> marketplace_product_3.html

Form/message-box-large.html
=> created html large message box

Form/search-zip-large.html
=> search-zip-large.html

Form/search-category-large.html
Solving issue #355
PrintScreen of the new component created using [Tailwind Playgrounds](https://play.tailwindcss.com/):
=> created search-category-large.html

Navbar/navbar_6.html
=> navbar_6.html

Navbar/navbar_10.html
=> navbar_10.html

Form/email-with-button-large.html
Here's a screenshot of the component I created.
Sorry for getting little late tho :)
=> Email form with large button

Navbar/navbar_16.html
=> navbar_16.html

Footer/footer-6.html
**Description**
1. What is this PR about?
#422 
2. Write individual changes in points
- Added footer component (No. 6)
3. Add Screenshot/Gifs covering what changed?
> Desktop Dark/Light Theme
> Tab Device Dark/Light Theme
> Mobile Device Dark/Light Theme
=> Issue #422: added footer component (No. 6)

Form/form-file-large-form.html
=> Create a file large form

Avatar/index.html
**Description**
1. What is this PR about?
#414 
2. Write individual changes in points
- Added Avatar components (Squared & Rounded)
3. Add Screenshot/Gifs covering what changed?
=> Issue #414: added avatar components

Buttons/button_secondary_rounded_icon.html, Footer/Footer 11 lift blue.html, Footer/Footer 11 white.html, Navbar/navbar_0.html
=> Solved Issue #22 Added Secondary icon button rounded 

Navbar/navbar_0.html
=> Added Navbar 0 issue #408

Footer/Footer 11 lift blue.html, Footer/Footer 11 white.html, Navbar/navbar_0.html
=> Added Footer 11 lift blue #435

Footer/Footer 11 white.html, Navbar/navbar_0.html
=> Added Footer 11 white #384

Accordion/index.html
=> Added accordion component

Breadcrumb/Breadcumb.html
=> Solved issue #445 Breadcrumb added

Navbar/navbar_15.html
=> navbar_15.html

Footer/footer-black4.html, Testimonials/basic-testimonial-card.html
- used icon from fontawesome.
- only footer component code is present in file without html boilerplate
- cdn link to fontawesome and tailwind css are provided in the start of file
- couldn't find the color code for desired background-color
- couldn't find 'LIFT' logo
-
=> Footer-black4 created using tailwind css.

Feature Cards/Features card medium filled.html, Footer/Footer 11 dark.html
=> Added Features card medium filled

Footer/Footer 11 dark.html
=> Solved issue #448  Added Footer 11 dark

Feature Cards/Features card medium filled.html, Footer/Footer 11 dark.html, Navbar/navbar_1.html
=> Added Navbar 1

Footer/footer_black_1.html
You have accidently closed this issue #420 which is assigned to me
screenshot
=> footer_black_1.html

Navbar/navbar_01_V2.html
=> navbar_01_V2.html

Footer/footer_blue_1.html
=> footer_blue_1.html

Content Cards/content_card_6.html, Feature Cards/Feature_card_item_21.html
=> Added Content Card 6

Feature Cards/Feature_card_item_21.html
=> Added Feature Card item 21

Form/form-email-form.html, Form/form-email-large-form.html
Thank you for this opportunity. I changed a file by mistake but have reversed the changes.
=> Created large email form

Footer/footer-white-2.html
=> footer white-2 added

Footer/footer-white1.html
The screenshot of the created component
=> Created footer-white1.html

Form groups/email_form_group_large.html
=> Added Email form group large

Footer/footer-3-white.html
=> add footer-3-white

Footer/footer-white17.html
=> added footer-white17

Footer/footer-black17.html
preview:
https://play.tailwindcss.com/joPmamQUqq?layout=preview
=> created footer-black17

Footer/footer-blue3.html
=> Created a footer-blue3

Footer-blue/index.html
[https://github.com/Clueless-Community/web-ui-kit/issues/466](url)
=> Create a footer blue-17 #466

Navbar/nav-mobile/nav-5.html
=> Created Mobile Nav-5

Footer/footer-black-2.html
=> footer-black-2 added

Avatar/avatar-group.html
**Description**
1. What is this PR about?
#513 
2. Write individual changes in points
- Added Avatar Group component (w/ example)
3. Add Screenshot/Gifs covering what changed?
=> Issue #513: added avatar group component

Buttons/button_group.html
**Description**
1. What is this PR about?
#511 
2. Write individual changes in points
- Added Button Group component (Solid & Outlined)
3. Add Screenshot/Gifs covering what changed?
=> Issue #511: added button group component

Footer/footer-black-3.html
=> footer black 3 added

Footer/footer-black3.html
=> Created footer-black3.html

Footer/footer 11 blue.html
=> Added Footer 11 blue

Navbar/navbar_17.html
=> navbar_17.html

Footer/footer_blue_12.html
=> footer_blue _2.html

footer_black_12.html
=> footer_black_12.html

Footer/footer-18-white.html
I built footer 18 white. #468 
Here is a screenshot:
=> add footer 18 white

Footer/footer-black-14.html
Here, I have added footer-black-14 by using html and tailwind css.
=> added footer-black-14

Processing button/processing_button.html
Added Button with loading animated spinner made using Tailwind CSS
Live demo : https://play.tailwindcss.com/ynIHOMB2TF
=> Added Processing button component

Footer/footer-white-10.html
Add footer white variation 10
Ref: Clueless-Community/web-ui-kit#565
Tailwindcss playground - [https://play.tailwindcss.com/J6bU83BAp1?layout=preview](https://play.tailwindcss.com/J6bU83BAp1?layout=preview)
=> Add footer white variation 10

Footer/footer-dark-10.html
Issue No: https://github.com/Clueless-Community/web-ui-kit/issues/562
Output at Tailwind Play:
=> Create a Footer Dark 10

Filters/desktop/marketplace-2.html
In Figma file it was colored completed , but code is not present for this desktop filter . 
screenshot:
=> marketplace-2.html

Navbar/navbar-11.html
https://user-images.githubusercontent.com/115935687/198815367-4f927044-871e-43e6-9b6e-4135f7c8320b.png
link for the screenshot of the navbar
added the file called navbar-11
=> added navbar 11

Navbar/navbar-14.html
Issue Link: https://github.com/Clueless-Community/web-ui-kit/issues/600
Tailwind Playground Image:
=> Create a navbar-14

Filters/desktop/marketplace_desktop_filter_5.html
=> marketplace_desktop_filter_5.html

Filters/desktop/marketplace_filter_2_1.html
=> marketplace_filter_2_1.html

Filters/mobile/Mobile_Filter_Vertical_2.html
Regarding #482 
Hey, I have created a vertically long mobile filter component using Tailwind CSS consisting of three parts: Accessories, Clothing, and Entertainment
( it is not possible to take an image consisting of all three parts bcz it is in a vertical manner and long too So to solve this I am attaching a separate image of all parts )  
1. Accessories
2. Clothing
3. Entertainment
Kindly, review my PR, and In case of suggestions feel free to discuss them with me.
Thanks 💛
=> Vertical_2 mobile_filter added

Footer/footer-black18.html
Issue Link; https://github.com/Clueless-Community/web-ui-kit/issues/471
Tailwind Playground Image:
=> Create a footer black-18

Content Cards/content-card-3.html, Content Cards/content-card-4.html
Here is the component I have created -->
#626
=> Content card 3

Content Cards/content-card-3.html, Content Cards/content-card-7.html
Here is the component I have created -->
#632
=> Content card 7

Content Cards/content-card-3.html, Content Cards/content-card-6.html
Here is the component I have created -->
#630
=> Content card 5

Filters/desktop/marketplace_desktop_filter_range.html
=> marketplace_desktop_filter_range.html

Form/form-success.html
hello, I have added a component for successful input
=> form-success

Avatar/src/avatar-text.html
**Here is the component I have built:-** 
I have built the Avatar component in avatar-text.html  for issue #668 
I have adjusted the height and width of the avatar and added border of gray color and a little box shadow 
**Here is a screenshot of that.**
Please Check @Rajdip019
=> Avatar's height and width Fixed

Avatar/src/avatar-status.html
Fix height and width in avatar status html
=> Fix height and width in avatar-status

Breadcrumb/src/Breadcrumb-2.html
**Here is the component I have built.**
I built Breadcrumb 2 which is just like Breadcrumb.html but with more style changes for the issue #676 
**_Before:-_**
**_After:-_**
=> Created Breadcrumb 2 by improving Breadcrumb

Badges/badges.design-system.mdx
I have  updated the badge design system file.
=> Updated Badge design system file

Footer/src/footer-blue-14.html
=> footer-blue-14

Buttons/src/Secondary/text-button-rounded.html
**Here is the component I have built.**
I have added the component Secondary rounded text button at  `Button/src/Secondary/text-button-rounded.html`
=> Secondary Rounded Text Button Component added

Navbar/src/navbar-0.html
Navbar/src/navbar-0.html logo text has been improved as per the design system.
text-xl changes to text-lg + font-semibold
=> logo text improved as per Navbar Design System

Navbar/src/navbar-02.html
issue #705 Solved: Search Bar Activated i.e. now, user can type in the input box
Hamburger hidden in all view except for mobile or tablet
Everything is now Fully responsive.
For Big Screen
For Small screen 
for tab and mobile
=> search bar activated, hamburger adjusted & now mobile responsive

Navbar/src/navbar-06.html
=> Hamburger menu button fixed

Content Cards/src/content-card-4.html, Navbar/src/navbar-06.html
I have solved issue #725 
Made Content card/src/content-card-4.html Responsive for mobile devices too.
=> Content card made resposive for mobile screen

Navbar/src/navbar-07.html
Issue #723 fixed
1) text size of Login updated as per navbar design system
2) hovering on About and Contact now changes color to be blue-600
=> login button updated and nav tag fixed

Navbar/src/navbar-08.html
I have fixed the text color issue #730 
Changed nav tag text color as per navbar design system.
In normal it will be text-gray-600 and on hover it will be text-blue-600
=> Navbar 8 tag text color on hover fixed 

Navbar/src/navbar-09.html
=> Navbar 9 made responsive for all breakpoints

Contact/src/contact-4.html
Design of contact-4.html has been updated as per SeamLess UI design system and Made Responsive for all screen
=> Contact-4 made responsive and design updated

Navbar/src/navbar-05.html
=> Added Navbar-05

Footer/src/footer-blue-05.html
=> Added footer-blue-05

Book appointment component/src/book-appointment-0.html
For Issue #744 
1)As discussed need to remove Pink Border  - DONE
2)Use SeamLess UI Form components instead of the ones used.  - DONE
3)Make It responsive for Mobile Screens.  - DONE
=> Book Appointement Design updated and made responsive

Others/MovieCard-Componenet.html
#Successfully completed issue no #740
Please check and merged
Final output something like this.
https://play.tailwindcss.com/SqiPHDQYac
=> MovieCard-Componenet.html

Contact/src/contact-3.html
For issue #746 
I have made the component responsive and have updated the form section in the code and used the SeamLess UI Form component.
=> Contact 3 made responsive and Design updated

Footer/src/footer-dark-13.html
Made footer-dark-13 responsive. Screenshots attached.
On large screens:
On mobile screens:
=> Made footer-dark-13 responsive

Navbar/src/navbar-16.html
I have Improved the Navbar 16 and made it responsive at `Navbar/srv/navbar-16.html`
=> Navbar 16 Improved & Made Responsive

Navbar/src/navbar-16.html, Navbar/src/navbar-17.html
I have Improved the Navbar 17 and made it responsive at `Navbar/srv/navbar-17.html`
**_Full Screen View_**
=> Navbar 17 Improved & Made Responsive

Footer/src/footer-blue-13.html, Footer/src/footer-dark-13.html
Made Footer-blue-13 responsive. Screenshots attached below.
When viewed on large screens:
When viewed on mobile screens:
=> Made Footer-blue -13 responsive

Footer/src/footer-blue-13.html, Footer/src/footer-dark-13.html, Footer/src/footer-white-13.html
Two issues solved:
1. Added footer white-13
2. Made footer-white-13 responsive
Screenshots attached below:
When viewed on large screens:
When viewed on mobile screens:
=> Added footer-white-13 and made it responsive

Filters/src/mobile/marketplace-2.html
For Issue #782 `Filter/src/mobile/marketplace-2.html`
=> fixed marketplace 2

Buttons/README.md
=> Button Readme Updated

Navbar/src/navbar-21.html
=> improved Nav 21

Footer/src/footer-blue-11.html
Solved #849 . Improved footer-blue-11 and made it responsive. Attached screenshots:
=> Improved footer-blue-11 and made it responsive

Footer/src/footer-white-11.html
Solved #851 . Improved footer-white-11 and made it responsive. Screenshots attached:
=> Improved footer-white-11 and made it responsive

Footer/src/footer-dark-10.html
Solved #847 . Improved footer-dark-10 and made it responsive. Screenshots attached.
=> Improved footer-dark-10 and made it responsive

Footer/src/footer-white-10.html
Solved #846 . Improved footer-white-10 and made it responsive. Attached screenshots:
=> Improved footer-white-10 and made it responsive

Inputs/inputs.design-system.mdx, Tables/table.design-system.mdx
Please review my changes
- #818 
- #820
=> Input and  table design system updated

Rating/rating.style-guide.mdx
Please review my Changes
- #816
=> rating style guide updated

Footer/src/footer-blue-17.html
Improved footer-blue-17 and made it responsive. Attached screenshots
=> Improved footer-blue-17 and made it responsive

Footer/src/footer-white-17.html
Improved footer-white-17 and made it responsive. Attached screenshots.
=> Improved footer-white-17 and made it responsive

Footer/src/footer-dark-17.html
Solved #877 . Improved footer-dark-17 and made it responsive. Attached screenshots:
=> Improved footer-dark-17 and made it responsive

Avatar/src/avatar-group.html, Avatar/src/avatar-status.html, Avatar/src/avatar-text.html, Avatar/src/avatar.html
=> image issue resolved

Avatar/avatar.design-system.mdx
=> avatar design system created

Pricing Components/src/pricing-card-5.html
=> Improved Pricing Card 5 

Pricing Components/src/pricing-card-2.html, Pricing Components/src/pricing-card-5.html
=> Improved Pricing card 2

Testimonials/src/testimonial-7.html
=> Testimonial 7 made responsive 

Testimonials/src/testimonial-7.html, Testimonials/src/testimonial-8.html
=> Testimonial 8 made responsive

Content Cards/src/content-card-3.html
Closes #932 . Improved content-card-3. Screenshots attached.
=> Improved content-card-3

Content Cards/src/content-card-6.html
Closes #933 . Improved content-card-6 and added video. Attached video preview:
https://user-images.githubusercontent.com/66685553/208154993-aa8787ed-449a-485b-b0c3-b335e7c39d21.mp4
=> Improved content-card-6

Feature Cards/README.md
added clickable links to the image and put it the table formate
=> Update Feature Card readme

Contact/src/contact-5.html, Contact/src/contact-6.html, Product Cards/src/product-card-3.html
=> Improved Product Card 3 and made responsive

Contact/src/contact-5.html, Contact/src/contact-6.html
For Issue #938 
I have merged Book appointment components to contact and deleted Book Appointment folder
=> Contact 5 and 6 added from Book Appointment 

Widgets/src/widget-4.html
Closes #961 . Improved widget-4. Added hover effect. Made it responsive.
Attached screenshots:
=> Improved widget-4

Tables/src/primary-table-light.html
Closes #958 . Made primary-table-light responsive. Screenshots attached.
=> Made primary-table-light responsive

Tables/src/primary-table-dark.html
Closes #957 . Made primary-table-dark responsive. Screenshots attached
=> Made primary-table-dark responsive

Dropdown/src/dropdown-1.html, Product Cards/src/product-card-4.html
=> Wokring Dropdown 1 added

Product Cards/src/product-card-4.html
=> Product card 4 made responsive

Dropdown/src/dropdown-1.html, Dropdown/src/dropdown-2.html, Product Cards/src/product-card-4.html
=> Working Dropdown 2 added

Timeline/src/timeline-2.html
Closes #984 . Improved timeline-2. Attached screenshots.
=> Improved timeline-2

Widgets/src/widget-6.html
Closes #978 . Added widget-6. Screenshots attached.
=> Added widget-6

Filters/src/mobile/marketplace-1.html
=> Marketplace card 1 made responsive

Filters/src/desktop/desktop_filter_style_2.html, Filters/src/mobile/marketplace-1.html
=> Filter Style 2 made responsive and working dropdown added

Filters/src/desktop/desktop_filter_style_2.html, Filters/src/desktop/marketplace_desktop_filter_5.html, Filters/src/mobile/marketplace-1.html
=> Card made Responsive

Filters/src/desktop/desktop_filter_style_2.html, Filters/src/desktop/marketplace_desktop_filter_5.html, Filters/src/desktop/marketplace_desktop_filter_range.html, Filters/src/mobile/marketplace-1.html
=> Range Card made responsive

Filters/src/desktop/desktop_filter_style_2.html, Filters/src/desktop/marketplace-2.html, Filters/src/desktop/marketplace-products.html, Filters/src/desktop/marketplace_desktop_filter_5.html, Filters/src/desktop/marketplace_desktop_filter_range.html, Filters/src/mobile/marketplace-1.html
=> Marketplace Products Card updated

Footer/src/footer-dark-01.html
=> footer dark 1 corrected

Accordion/src/accordion-0.html
Closes #998 . 
1. Improved the design of accordian-0
2. Made the dropdown button working
3. Made it responsive
Attached video preview:
https://user-images.githubusercontent.com/66685553/208288245-9dc6301a-e0a9-4144-9116-92784ac556ef.mp4
=> Improved accordian-0 and made it responsive

Accordion/src/accordion-1.html
Closes #999  . 
1. Improved the design of accordian-1
2. Made the dropdown button working
3. Made it responsive
Attached video preview:
https://user-images.githubusercontent.com/66685553/208288241-4c83b55f-96ff-4e14-a1c1-eba7a4e86b2b.mp4
=> Improved accordian-1 and made it responsive

Accordion/src/accordion-2.html
Closes #1000 . 
1. Improved the design of accordian-2
2. Made the dropdown button working
3. Made it responsive
Attached video preview:
https://user-images.githubusercontent.com/66685553/208288243-977901c5-2299-413d-93d5-ef61d7a168dc.mp4
=> Improved accordian-2 and made it responsive

Footer/src/footer-blue-01.html
=> footer blue 1 design corrected

Others/task_list.html
=> Added the task list.html

Stats/src/stats-0.html
Updated a fresh look to UI for stats-0.html
Improved version:
=> Improved a better UI for stats-0.html

Filters/src/mobile/marketplace-product-2.html
Closes #1039 . Improved marketplace-product-2. Attached screenshots:
=> Improved marketplace-product-2

Badges/README.md, Badges/src/badge-0.html
Closes #1035 . Created readme for badges.
=> Created readme for badges

Avatar/README.md
Closes #1033  . Created readme for avatar.
=> Created readme for avatar

Form/src/search.html
Closes #1045 . Improved the form search field. Screenshots attached.
=> Improved the form search field

Form groups/src/search-with-category-and-btn-horizontal.html
Closes #1044 . Improved search-with-category form.
1. Improved the UI
2. Made dropdown working
=> Improved search-with-category form

Breadcrumb/README.md, Breadcrumb/breadcrum.design-system.mdx
=> Breadcrumb Readme Added

Form/src/checkbox.html
https://play.tailwindcss.com/ZNOAsoRV9D
#1060
=> Create  checkbox.html

Others/header_banner.html
the button colour matched with the header colour so changed it to red
=> Header_banner updated with blue 600 and primary button 

Alerts/README.md, Alerts/src/modern.html, Alerts/src/morden.html
Closes #1070 . Created readme for alerts. Screenshots attached.
=> Created readme for alerts

Form groups/README.md
Closes #1096 . Created readme for Form groups. Screenshots attached.
=> Created readme for Form groups

Filters/src/desktop/marketplace-4.html, Filters/src/mobile/marketplace-3.html
=> Mobile Combined Filter Added

Filters/src/desktop/marketplace-4.html
=> Desktop Combined filter Added

Navbar/src/Nav-mobile/nav-8.html
Closes #1139 . Added Navbar mobile nav-8. Screenshot attached.
=> Added Navbar mobile nav-8

Navbar/src/Nav-mobile/nav-4.html
Closes #1138 . Improved Navbar nav-4 and made it responsive. Screenshots attached.
=> Improved Navbar nav-4 and made it responsive

Navbar/src/Nav-mobile/nav-3.html
Closes #1137 . Improved Navbar mobile nav-3. Screenshots attached.
=> Improved Navbar mobile nav-3

Pricing Components/README.md
Closes #1130 . Created readme for pricing components. Screenshot attached.
=> Created readme for pricing components

Others/assigned.html, Others/card_footer.html, Others/header_banner.html
=> Footer_with page info

Others/assigned.html, Others/avatar_chips.html
=> Avatar Chips added

Others/graph-01.html
Added graph-01.html to others section.
Additional chart.js was used while creating this component.
Closes issue: close #1141
Preview:
=> Added graph-01.html

Navbar/src/navbar-19.html
Closes #1187 . Improved nav-19. Screenshots attached.
=> Improved nav-19

Breadcrumb/src/breadcrumb-3.html, Others/assigned.html, Others/avatar_chips.html, Others/collapser.html, Others/multiple_collapser.html
=> Breadcrumb added 

Dropdown/README.md
Closes #1203 . Created a readme for dropdown. Screenshot attached.
=> Created a readme for dropdown

Footer/src/footer-white-18.html
I have made Footer White 18 again which looks close to Figma design 
---
=> footer White 18 Improved

Stats/README.md
Closes #1205 . Created a readme for stats. Screenshots attached.
=> Created a readme for stats

Footer/src/footer-blue-18.html, Footer/src/footer-white-18.html
I have made Footer Blue 18 and tried to make it close to figma design
---
=> Footer Blue 18 Improved

Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
I have Improved Footer Dark 18 and tried to make it close to figma design
---
=> Footer Dark 18 Improved

Breadcrumb/src/breadcrumb-3.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
=> Improved Breadcrumb 3 

Breadcrumb/src/breadcrumb-3.html, Filters/src/mobile/marketplace-2.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
check live https://play.tailwindcss.com/HTzwOB7oaY
=> Mobile Filter marketplace 2 Improved

Breadcrumb/src/breadcrumb-3.html, Filters/src/mobile/marketplace-2.html, Filters/src/mobile/range_filter.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
=> Improved Range Filter 

Breadcrumb/src/breadcrumb-3.html, Filters/src/mobile/marketplace-2.html, Filters/src/mobile/marketplace-3.html, Filters/src/mobile/range_filter.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
=> Updated Big Mobile Filter 

Breadcrumb/src/breadcrumb-3.html, Filters/src/desktop/marketplace-products.html, Filters/src/mobile/marketplace-2.html, Filters/src/mobile/marketplace-3.html, Filters/src/mobile/range_filter.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
=> Filters Desktop Marketplace Products Improved

Breadcrumb/src/breadcrumb-3.html, Filters/src/desktop/marketplace-4.html, Filters/src/desktop/marketplace-products.html, Filters/src/mobile/marketplace-2.html, Filters/src/mobile/marketplace-3.html, Filters/src/mobile/range_filter.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
###See Before and After in this clip
https://user-images.githubusercontent.com/98400348/209420186-15d2cf0a-1102-4064-a20d-f84d43034b70.mp4
=> Full Dektop Filter Improved

Breadcrumb/src/breadcrumb-3.html, Filters/src/desktop/desktop_filter_style_2.html, Filters/src/mobile/marketplace-2.html, Filters/src/mobile/marketplace-3.html, Filters/src/mobile/range_filter.html, Footer/src/footer-blue-18.html, Footer/src/footer-dark-18.html, Footer/src/footer-white-18.html
=> Improved desktop filter

Footer/src/footer-blue-17.html, Footer/src/footer-dark-17.html, Footer/src/footer-white-17.html, Inputs/src/email.html, Inputs/src/textarea.html
Added Logo  &
changed whole text color as per figma design
Also improved Circular Design at the corners
=> Improved Footer Dark 17

Inputs/src/email.html, Inputs/src/textarea.html
I have removed two file from `Inputs/src/email.html` and `Inputs/src/textarea.html` because both of these are already present in the form section or Form groups section
=> Removed the duplicate files from Inputs

Footer/src/footer-white-17.html, Inputs/src/email.html, Inputs/src/textarea.html
Added Logo  &
changed whole text color as per figma design
Also Fixed Circular Design improved
=> Improved Footer White 17 

Footer/src/footer-blue-17.html, Footer/src/footer-white-17.html, Inputs/src/email.html, Inputs/src/textarea.html
Added Logo  &
changed whole text color as per figma design
Also Fixed Circular Design improved
=> Improved Footer Blue 17 

Footer/src/footer-white-14.html
Closes #1257 . Improved footer-white-14. Screenshot attached
=> Improved footer-white-14

Team/Readme.md, Timeline/src/readme.md
=> created readme for Team

Timeline/src/readme.md
=> created readme for timeline

Feedback_Form/readme.md, Team/Readme.md, Timeline/src/readme.md
=> created readme for Feedback Forms

Filters/README.md, Filters/src/mobile/marketplace-1.html, Filters/src/mobile/marketplace-product-1.html
Closes #1204 . Created a readme for filters. Attached screenshots.
=> Created a readme for filters

Content Cards/README.md
=> Update content card readme.md

Others/readme.md
=> updated  readme.md for others 

Feedback Form/readme.md
=> create readme.md file of feedback form

Timeline/src/timeline-1.html, Timeline/src/timeline-2.html
The dark mode feature for Timeline-1.html and Timeline-2.html has been added to their respective files.
Issue Closed: close #1267 #1268
@rupsha014
=> Added the dark mode feature

Footer/src/footer-dark-16.html
Resolved #1365 
Bg color changes from bg-slate-900 to #0A142F
=> Improved footer dark 16

Footer/src/footer-dark-13.html
Resolved #1361 
Changes Made:-
1) bg color changed as per figma design
2) Logo changes as per figma design
3) Replaced socials as per figma design
4) padding x AND y re-aligned
5) Back to top button realigned
=> Improved Footer Dark 13

Testimonials/README.md
=> Update README.md for Testimonials

Feedback Form/readme.md
=> Updated readme.md for Feedback forms

Movie Card/Readme.md
=> Updated Readme.md for Movie_card

Feature Cards/README.md
=> Feature Card  Readme updated

Others/collapser.html
https://play.tailwindcss.com/D6rlp9VvXu
=> Working collapser added

Others/multiple_collapser.html
=> Wokring collapser added

Others/multiple_collapser.html, Others/readme.md
=> Improved Others Readme Images

Widgets/src/widget-3.html
=> Improved Widget 3

Widgets/README.md
I have updated widgets Readme Screenshots as per recent changes
=> Updated Readme.md

Store Buttons/store-buttons.design-system.mdx
successfully resolve the issue #1454 
@Rajdip019 please check it once I have done changes to improve the design system
=> Improve the design system of store button

Testimonials/src/testimonial-8.html
>Made user image relative to the div so now it moves along with the whole div
---
>here i applied ml-36, only main content moved and not the user image
>made user image relative to the component div and re-aligned it as per figma design
=> Improved Testimonial 8

Movie Card/movie_card.design-system.mdx
#Successfully completed issue no #1524 
Please check and merged
=> Update Movie design system mdx

Feedback Form/feedback-form.style-guide.mdx
#Successfully completed issue no #1526 
Please check and merged
=> Update feedback desgin system

Stats/stats.design-system.mdx
#Successfully completed issue no #1527 
Please check and merged
=> Update stats design system

Inputs/inputs.design-system.mdx
enhancements have been made to the design system file
=> Updated inputs.design-system.mdx

Breadcrumb/README.md
=> Updated Breadcrumbs/Readme, removed breadcrumb4

Feature Cards/src/feature-card-30-black.html
Closes #1718
This is the screenshot  of the component
=> created feature card 30 black

Feature Cards/src/feature-card-18-black.html
This PR is raised for issue - #1772. Please review it.
=> Added text-center class to p tag

Feature Cards/src/feature-card-30-white.html
closes #1720 
<b> ScreenShot</b>
=> Created feature Card 30 white #1720

pricing-car-0-blue.html
I have created pricing card-0 blue 
closes (#1913)
=> I have created Pricing card blue

Content Cards/src/content-card-15.html
Created Content-Card-15 using HTML and Tailwind CSS. Used default Tailwind values to replicate the Figma Design.
closes #1796
=> Created Content-Card-15

Product Cards/src/product-card-3-blue.html
closes #1877 
https://user-images.githubusercontent.com/110401845/220355330-4f1a220a-e69a-471b-aa76-18f3768be511.mp4
=> added product-card-3-black

Pricing Components/src/pricing-card-1-white.html
=> Created Pricing card 1 white

Product Cards/src/product-card-2-black.html
=> product card 2 black added

Pricing Components/src/pricing-card-1-blue.html
Solved the closes #1915 which was to create  Pricing card 1 blue.
Here is the image of final component
=> Created pricing-card-1-blue.

Product Cards/src/product-card-4-black.html
#Description
Added product card 4 black 
closes #1888
=> Added product card 4 black

Product Cards/src/product-card-4-blue.html
=> Create Product Card 4 blue #1889, Solved

Pricing Components/src/pricing-card-4-blue.html
=> Created Pricing card 4 blue

Pricing Components/src/pricing-card-4-white.html
=> Created pricing card 4 white

Pricing Components/src/pricing-card-2-black.html
=> Create Pricing Card 2 black

Pricing Components/src/pricing-card-2-white.html
=> Create Pricing Card 2 white #1945 , Solved 

Pricing Components/src/pricing-card-2-blue.html
=> Create Pricing Card 2 Blue #1942 . 

Pricing Components/src/pricing-card-1-black.html
Here is the component I have built (Pricing Card 1 Black). 
=> Create Pricing Card 1 Black #1917

Content Cards/src/content-card-12.html
=> Add: `ContentCard-12`

Product Cards/src/product-card-2-white.html
Created product-card-2-white.html
closes #1892
=> Created product-card-2-white.html

Product Cards/src/Product-card-1-white.html
Added the Product card 1 white.
Fixes #1904
=> Added Product Card 1 white

Pricing Components/src/pricing-card-5-white.html
Closes #1941
This is the screenshot of the component in smaller view
=> Created Pricing card 5 white

Pricing Components/src/pricing-card-5-blue.html
Closes #1940
This is the screenshot of the component in smaller view
=> Created pricing card 5 blue

Pricing Components/src/pricing-card-5-black.html
Closes #1939
This is the screenshot of the component in a smaller view
=> Created pricing card 5 black

Product Cards/src/product-card-4-white.html
Closes #1890
This is the screenshot of the component in a smaller view
=> Created product card 4 white

Content Cards/src/content-card-13.html
=> Closes #1789 [`Content-Card-13`]

Form/src/switch-buttons-black.html
=> created switch-buttons-black file

Form/src/error-rounded-white.html
=> Created error rounded white

Form/src/error-rounded-black.html
=> Created error rounded black

Form/src/success-rounded-black.html
=> Created success rounded black

Store Buttons/src/store-button-google-play-white.html
closes #1977 
Created a google play white button pls check
=> Create Google play button white #1977, Solved

Form/src/email-rounded-black.html
Updated the Email rounded black
changed the text color. 
fixes #1994
=> text color changed

Form/src/radio-button-white.html
=> made radio button white

Form/src/radio-button-black.html
=> Update radio black

Form/src/radio-button-black.html
=> added radio-button-black file

Form/src/email-rounded-white.html
=> email-rounded-white

Form/src/message-textarea-rounded-black.html
Solved issue no #2006 which was to create Message Textarea Rounded Black
Here is the image of final component
=> Created message textarea rounded black

Form/src/select-black.html
=> #2008  created select-black

Form/src/select-white.html
Here is the component I have built (Select White).
=> Create Select White #2007

Accordion/README.md, Accordion/accordion.design-system.mdx, Accordion/src/accordion-3.html
=> Accordion-3 updated

Product Cards/src/Product-card-3-white.html
=> added product-card-3-white file

Avatar/README.md
Closes #2067
This is the screenshot
=> Updated Avatars Readme

Alerts/README.md
Closes #2066
This is screenshot
=> Updated Alerts Readme

Content Cards/src/content-card-13-blue.html
=>  Added content card 13 blue

Pricing Components/README.md
#2042 Successfully updated.
@RavindraP04 Plz review and let me know is it need further modification.
Can't wait to see my first pr merged in jwoc
=> Update Pricing Card Readme

Product Cards/README.md
=> Product card Readme updated

Testimonials/src/testimonial-1-blue.html
=> Image link is replaced in testimonial-1-blue

Badges/README.md
Closes #2069
This is the screenshot
=> Updated badges Readme

Breadcrumb/src/breadcrumb-3.html
=> improved breadcrumb 3

Avatar/src/avatar-group.html
=> Updated Avatar-group.html

Testimonials/src/testimonial-1-black.html
=> Image is replaced in testimonial-black-1

Others/collapser-2.html
issue resolved
#2051 
https://user-images.githubusercontent.com/49303222/229061067-3f0e74c9-3f07-4977-bdb7-e2ba28ee89d3.mp4
=> Created Collapser with View More and Shrink #2051

database/alerts/alertGeneralMetaData.ts, database/alerts/alertInfoMetaData.ts, database/alerts/alerts.tsx, pages/docs/components/alerts.mdx, pages/docs/components/buttons.mdx
=> 2 alerts added

pages/docs/introduction.mdx
Hi there,
I noticed some spelling mistakes and grammatical errors in the introduction page of the documentation. I have gone ahead and made some improvements to the text to correct these issues.
I believe that these changes will make the documentation more polished and easier to understand for users.
Please let me know if there are any further changes that need to be made or if you have any feedback on the changes I made.
Thank you!
Issue: #2185
=> Documentation: Fix spelling and grammar errors in introduction page

Tutorial.md
…s/2190)
There was a Simple Change regarding the word.
=> Fixed [#2190] : Incorrect Link text - "Tailwind Git" in Tutorial.md 

components/Web.tsx
https://github.com/Clueless-Community/seamless-ui/issues/2233
Fixed image size web component.
For the mobile screen changed the size of image in the card at 360px.
set the width property to fix it
=> Fixed image size in Web component

components/Hero.tsx, components/Web.tsx
=> Web Component image size issue fixed

styles.css
> closes #2236 
Preview the PR [here](https://seamless-ui-git-fork-520541-officialcluelesscommunity-gmailcom.vercel.app/)
=> Issue #2236 : Customized the default scrollbar

components/Product.tsx
**Title:** Update text styles in Product.tsx
**Description:**
This PR updates the text styles of the website. Specifically, it reduces the size of the main header and adds padding to the description paragraph to improve readability.
**Changes Made:**
- Updated main header text size to 3xl
- Added left padding to description paragraph
**Reason for Changes:**
The previous styles were making the text difficult to read on smaller screens, so I made these changes to improve the overall user experience. 
Fixes #2238
=> Fixed Product Section

components/Footer.tsx, components/Maintainers.tsx
=> footer date and copyright issue fixed 

components/Footer.tsx
=> Footer made responsive

components/Footer.tsx, components/Hero.tsx
Merging branch `website-dev` to `website-prod`
Footer made responsive 
Footer design updated as per Figma design
Issue #2239 
PR #2275
=> Footer Responsiveness Issue fixed merge branch

components/Maintainers.tsx
=> Line alignment issue fixed in Maintainers.tsx

components/Footer.tsx, components/Maintainers.tsx
Merging branch `website-dev` to `website-prod`
Alignment of the curved line directing form Repo maintainers to the meet the maintainers line aligned correctly so that is does not over flows and design remains consistent as per the figma design
=> Maintainers.tsx curved arrow aligned

components/Time.tsx
closes #2279
The issue was in the `Time.tsx` section mainly with the timeline graph, below I have attached the before and after images
=> Time Section Aligned correctly 

components/Maintainers.tsx, components/Product.tsx, components/Time.tsx, components/Web.tsx
closes #2285
The button bg is green and text color is black but on hover, bg turns to dark green and text color becomes white
I have made changes to total 7 buttons in the home page and the components are Web.tsx, Time.tsx, Maintainers.tsx, Product.tsx
https://github.com/Clueless-Community/seamless-ui/assets/133729421/abe21054-a43f-45ef-94db-b713029bb61d
https://github.com/Clueless-Community/seamless-ui/assets/133729421/9f331870-f7e2-4a0f-9adb-715a3e02c3a3
=> Text color of all button in Home page fixed

components/Product.tsx
closes #2288
The `Visit Clueless` button in the bottom of the home page above the footer is behaving weirdly, the button is working even if it is clicked approx 20px upper side or in the down side,
The `button tag` was enclosed by `anchor tag` so the margin was given `my-9`  to the button because of which the the anchor tag was given padding so this issue was happening
=> Visit Clueless Button fixed 

.gitignore
Merging branch `website-dev` to `website-prod` for recent change in PR #2308 
The div in the `Web.tsx` is taking full width of the screen below the `md` size that is `768px` so I fixed it so that it does not expands
=> Card updated in Web.tsx 
